version: '3'

services:
    # notebooks:
    #     build: 
    #         context: ./
    #         dockerfile: ./notebookDocker/Dockerfile
    #     restart: always
    #     volumes:
    #         #use this for mac or linux
    #         # - ./:/home/jovyan/work
    #     ports:
    #         - '8888:8888'
    #     networks:
    #         - iwmi-net
    api:
        image: python:3.7
        build: 
            context: ./
            dockerfile: ./apiDocker/Dockerfile
        volumes:
          - ./api:/app
          - ./src:/app/src
        ports:
          - "8080:8080"
        networks:
          - iwmi-net
    web:
        image: node
        volumes:
          - ./web:/app
        command: bash -c "cd /app && npm i -g npm && npm i -g nodemon react-scripts && npm start"
        ports:
          - "3000:3000"
        networks:
          - iwmi-net
    elasticsearch:
        image: elasticsearch:7.8.0
        volumes:
            - ./esdata:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks: 
            - iwmi-net
        restart: on-failure
        environment: 
            discovery.type: single-node
    kibana:
        image: kibana:7.8.0
        ports: 
            - "5601:5601"
        networks:
            - iwmi-net
        links: 
            - elasticsearch:elasticsearch
networks: 
    iwmi-net:
        external: true